Add index.html
htmlacademy-adaptive/476339-mishka-22 pull request #2
Opened 2021-04-01 13:37 UTC by Palladii

2021-04-01 18:24 UTC, Pakistanka requested changes

2021-04-01 18:24 UTC, Pakistanka commented on source/index.html
> +<head>
Много ошибок валидации - https://prnt.sc/111rhb9
Проверь в https://validator.w3.org/nu/#textarea

2021-04-01 18:24 UTC, Pakistanka commented on source/index.html
> +        <li class="good__item"><a href="#">Предметы интерьера</a></li>
Потеряна буква s в конце слова good

2021-04-18 11:39 UTC, Palladii commented on source/index.html
> +        <li class="good__item"><a href="#">Предметы интерьера</a></li>
Исправила

2021-04-18 14:19 UTC, merged